In [1]:
import pandas as pd
import numpy as np
import indic

In [3]:
ind = indic.indices.split()
lista, k = [None]*len(ind), 0
for i in ind:
    lista[k] = pd.read_excel(i, sheet_name='Data', header=3)
    k+=1
lista[4]

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,52.410190,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,ALB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,157.343640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,AND,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,United Arab Emirates,ARE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.390320,NaN,NaN
7,Argentina,ARG,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,1028.258730,1032.769690,1120.707490,1177.004080,1199.404050,1193.853760,1202.070000,NaN,NaN,NaN
8,Armenia,ARM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,American Samoa,ASM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Australia,AUS,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,4335.390330,NaN,4530.727820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Austria,AUT,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,4141.924620,4145.700190,4359.027770,4405.952400,4695.264380,4763.259220,4883.857020,4955.032340,NaN,NaN
13,Azerbaijan,AZE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Burundi,BDI,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Belgium,BEL,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,3411.626980,3521.655390,3735.823350,3878.700070,4115.454540,4156.244320,4175.882360,4875.336220,NaN,NaN
16,Benin,BEN,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Burkina Faso,BFA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,47.495000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Bangladesh,BGD,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Bulgaria,BGR,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,1515.109970,1604.277290,1482.187090,1618.168080,1547.152340,1692.510720,1833.139200,1989.429890,NaN,NaN
20,Bahrain,BHR,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,361.986300,NaN,NaN,NaN
21,"Bahamas, The",BHS,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Bosnia and Herzegovina,BIH,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,150.793320,216.684410,266.689090,328.704270,NaN,NaN
23,Belarus,BLR,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Belize,BLZ,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Bermuda,BMU,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bolivia,BOL,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,145.714650,165.954260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Brazil,BRA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,618.828300,656.335270,698.102120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Barbados,BRB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Brunei Darussalam,BRN,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,459.904378,482.882061,503.331298,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Timor-Leste,TLS,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,599.972938,NaN,635.972380,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,Tonga,TON,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,South Asia (IDA & IBRD),TSA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,155.819497,NaN,NaN,NaN,NaN,225.774411,NaN,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,Trinidad and Tobago,TTO,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,Tunisia,TUN,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,1218.186890,1491.036010,1384.221400,1429.146370,1622.761670,1792.524710,1803.209550,1787.257610,NaN,NaN
242,Turkey,TUR,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,750.747600,810.517860,889.788330,980.842470,1097.172060,1168.598900,1156.512910,NaN,NaN,NaN
243,Tuvalu,TUV,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Tanzania,TZA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,35.041660,NaN,NaN,18.492050,NaN,NaN,NaN,NaN
245,Uganda,UGA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38.091170,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,Ukraine,UKR,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,1432.328540,1349.710680,1332.197910,1261.860490,1234.661580,1165.182200,1026.407490,1005.997220,NaN,NaN
247,Upper middle income,UMC,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,1101.748833,891.696831,940.947917,1012.931395,1063.554025,1110.655105,1223.609609,1318.486553,NaN,NaN
248,Uruguay,URY,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,273.663380,480.854870,549.132380,524.868490,537.277810,529.054110,504.164920,524.252120,NaN,NaN
249,United States,USA,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,3911.534500,4073.176330,3868.566440,4011.328620,4015.887080,4117.674090,4231.989280,NaN,NaN,NaN
250,Uzbekistan,UZB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,594.930700,588.226490,549.391840,533.730700,528.461170,522.502370,517.510860,514.660580,NaN,NaN
251,St. Vincent and the Grenadines,VCT,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,"Venezuela, RB",VEN,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,187.112890,182.396850,200.132810,228.356810,290.946970,357.840660,NaN,NaN,NaN,NaN
253,British Virgin Islands,VGB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Vietnam,VNM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,674.806760,NaN,NaN,NaN,NaN
256,Vanuatu,VUT,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,World,WLD,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1277.437640,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Samoa,WSM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,Kosovo,XKX,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,385.000750,388.159920,362.630220,385.071030,404.685900,437.055260,NaN,NaN,NaN,NaN
262,Zambia,ZMB,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,40.870550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Zimbabwe,ZWE,Researchers in R&D (per million people),SP.POP.SCIE.RD.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,89.609120,NaN,NaN,NaN,NaN,NaN

In [4]:
data,k,indices = pd.DataFrame(lista[0]['Country Name']),0, ['Country']
a = input("Ano")
for i in lista:
    indices += [ind[k].replace("_"," ").replace(".xls","")]
    data = data.join(i[a])
    data.columns = indices
    k+=1
data

Ano2016

,Country,High-technology exports,External debt stocks short-term,Inflation consumer prices,GINI index,Researchers in R&D,Agriculture forestry and fishing value added,Urban population,Foreign direct investment net inflows,Industry (including construction) value added,GDP per capita growth,Government expenditure on education total,Gross savings,Population growth,Time required to start a business,Total tax rate,Unemployment total,Ease of doing business index,Expense,GDP per capita
0,Aruba,1.158612e+06,NaN,-0.893020,NaN,NaN,NaN,43.192000,2.098217e+07,NaN,NaN,NaN,NaN,0.459929,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,2.054140e+08,2.169452,NaN,NaN,20.965898,25.020000,9.358944e+07,21.703995,-0.349412,NaN,18.096194,2.689163,7.500000,47.900000,8.841000,NaN,NaN,561.778746
2,Angola,NaN,1.539940e+08,34.736159,NaN,NaN,NaN,64.149000,4.104423e+09,NaN,-4.098056,NaN,3.049233,3.367572,36.000000,48.000000,7.724000,NaN,18.574540,3308.772828
3,Albania,8.424644e+06,1.892557e+09,1.282799,NaN,NaN,19.906724,58.421000,1.044188e+09,21.130734,3.517531,NaN,14.540693,-0.159880,5.000000,36.900000,15.220000,NaN,23.911715,4131.872341
4,Andorra,NaN,NaN,NaN,NaN,NaN,0.492101,88.248000,NaN,9.844719,2.855529,3.27811,NaN,-0.944017,NaN,NaN,NaN,NaN,NaN,37231.815671
5,Arab World,NaN,NaN,2.768466,NaN,NaN,5.690857,58.212637,3.856545e+10,39.212827,0.939868,NaN,23.757937,2.045601,23.168182,42.352381,10.019851,NaN,NaN,6151.180927
6,United Arab Emirates,4.291749e+08,NaN,1.617877,NaN,NaN,0.776055,85.965000,8.985705e+09,41.448681,1.707310,NaN,NaN,1.251759,8.200000,15.900000,1.636000,NaN,4.465958,38517.800386
7,Argentina,1.300926e+09,4.734073e+10,NaN,42.4,NaN,6.353904,91.627000,3.260164e+09,22.187498,-2.784592,NaN,12.403776,0.984742,24.000000,106.000000,8.696000,NaN,26.305915,12654.354999
8,Armenia,2.114263e+07,1.071620e+09,-1.271210,32.5,NaN,16.390474,63.082000,3.381152e+08,25.577133,-0.069478,2.75129,16.623303,0.269302,4.500000,18.500000,18.040001,NaN,25.711518,3605.743117
9,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,87.198000,NaN,NaN,-2.728006,NaN,NaN,0.111575,NaN,NaN,NaN,NaN,NaN,11834.745229
10,Antigua and Barbuda,NaN,NaN,-0.489438,NaN,NaN,1.642377,24.846000,4.893718e+07,17.512483,4.257367,NaN,NaN,1.035422,22.000000,41.900000,NaN,NaN,NaN,14462.176279
11,Australia,4.572081e+09,NaN,1.276991,NaN,NaN,2.430580,85.800000,4.257999e+10,22.258262,1.298225,NaN,20.732965,1.498210,2.500000,47.600000,5.720000,NaN,26.962637,49896.681101
12,Austria,2.100194e+10,NaN,0.891591,NaN,NaN,1.101589,57.905000,-2.994841e+10,24.710994,0.359740,NaN,26.202151,1.081396,21.000000,51.600000,6.010000,NaN,45.573072,44731.010855
13,Azerbaijan,9.132464e+06,1.461724e+09,4.179994,NaN,NaN,5.600000,55.021000,4.499666e+09,47.500000,-4.177172,NaN,22.649593,1.117857,4.500000,39.800000,5.000000,NaN,NaN,3880.738731
14,Burundi,NaN,2.650000e+05,5.538485,NaN,NaN,36.358803,12.388000,5.542036e+04,15.148674,-3.639518,NaN,-1.993923,3.135333,4.000000,40.100000,1.591000,NaN,NaN,285.727442
15,Belgium,3.806770e+10,NaN,1.972250,NaN,NaN,0.617492,97.919000,3.701322e+10,19.790923,0.900139,NaN,24.138765,0.506300,4.000000,58.700000,7.830000,NaN,41.445087,41260.977551
16,Benin,1.317651e+06,6.200300e+07,-0.930033,NaN,NaN,23.240416,46.229000,1.316859e+08,20.131315,1.131092,NaN,13.165722,2.763534,8.500000,57.400000,2.544000,NaN,NaN,788.532442
17,Burkina Faso,5.010517e+06,0.000000e+00,-0.247073,NaN,NaN,29.013187,28.134000,3.903114e+08,20.833936,2.880814,NaN,19.176727,2.915614,13.000000,41.300000,6.391000,NaN,16.475039,613.993127
18,Bangladesh,NaN,7.836438e+09,5.513526,32.4,NaN,14.045548,35.083000,2.326967e+09,27.346121,5.962689,2.50032,37.101730,1.080165,19.500000,34.400000,4.350000,NaN,9.418917,1358.779029
19,Bulgaria,1.185954e+09,8.609323e+09,-0.798523,NaN,NaN,4.054822,74.329000,1.655550e+09,24.426670,4.672685,NaN,26.501570,-0.701382,23.000000,27.000000,7.570000,NaN,32.361788,7469.447703
20,Bahrain,2.134316e+07,NaN,2.798520,NaN,NaN,0.333019,89.090000,2.433511e+08,39.426242,-0.645400,2.66452,23.934501,3.812797,9.300000,13.500000,1.215000,NaN,NaN,22560.581271
21,"Bahamas, The",NaN,NaN,-0.346377,NaN,NaN,0.880157,82.832000,7.372357e+07,12.325574,-2.793693,NaN,23.037035,1.129473,21.500000,33.800000,12.700000,NaN,16.898630,30260.305905
22,Bosnia and Herzegovina,9.349446e+07,6.865010e+08,-1.251444,NaN,NaN,6.370226,47.518000,2.725213e+08,23.166627,3.705578,NaN,12.177290,-0.542908,65.000000,22.600000,25.059999,NaN,35.326611,4808.636043
23,Belarus,6.056444e+08,1.062200e+10,11.836581,27.0,NaN,6.895281,77.661000,1.246900e+09,30.958409,-2.648714,4.97946,26.490065,0.125511,5.000000,52.700000,0.488000,NaN,29.629727,5022.626643
24,Belize,NaN,6.037000e+06,NaN,NaN,NaN,10.593780,45.495000,3.273341e+07,14.081652,-2.565463,NaN,11.439282,2.111220,43.000000,31.100000,7.910000,NaN,NaN,4960.181794
25,Bermuda,1.244848e+06,NaN,NaN,NaN,NaN,NaN,100.000000,8.177824e+07,NaN,NaN,NaN,NaN,0.156348,NaN,NaN,NaN,NaN,NaN,NaN
26,Bolivia,1.549372e+07,4.750000e+08,3.625239,44.6,NaN,11.171875,68.738000,3.353655e+08,25.326359,2.701313,NaN,15.311961,1.510047,45.000000,83.700000,3.060000,NaN,NaN,3117.330459
27,Brazil,9.775328e+09,5.720175e+10,8.739479,NaN,NaN,4.891386,86.042000,7.824838e+10,18.278791,-4.254147,NaN,13.989571,0.817556,79.500000,68.400000,11.610000,NaN,36.284749,8639.365743
28,Barbados,3.820140e+07,NaN,NaN,NaN,NaN,1.379980,31.193000,2.282921e+08,12.663804,1.721196,5.09272,NaN,0.273711,15.000000,34.700000,9.720000,NaN,NaN,15891.626549
29,Brunei Darussalam,NaN,NaN,-0.732323,NaN,NaN,1.203655,76.990000,-1.505508e+08,57.289364,-3.768599,4.42541,56.412016,1.345029,14.500000,8.000000,6.935000,NaN,NaN,26939.418047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,NaN,NaN,2.773160,NaN,NaN,5.068351,80.155959,1.688689e+11,23.546333,-1.501825,NaN,16.894733,1.080345,32.946667,45.906667,7.830381,NaN,29.245270,8260.906649
235,Timor-Leste,NaN,NaN,-1.220680,NaN,NaN,11.352940,29.850000,5.478700e+06,44.819133,-1.376379,NaN,14.163955,2.207092,9.000000,11.200000,3.366000,NaN,94.989516,1987.124857
236,Middle East & North Africa (IDA & IBRD countries),NaN,NaN,3.224713,NaN,NaN,9.845321,60.630644,2.053065e+10,33.854158,5.243349,NaN,NaN,1.691423,19.833333,41.025000,11.787197,NaN,NaN,3876.512617
237,Tonga,NaN,4.130000e+05,2.579998,NaN,NaN,17.211917,23.222000,8.855570e+06,17.268128,2.647956,NaN,NaN,0.710120,16.000000,27.500000,1.097000,NaN,NaN,3748.641794
238,South Asia (IDA & IBRD),NaN,NaN,4.182675,NaN,NaN,16.706026,33.123119,5.083489e+10,25.708253,5.492369,2.50032,30.961525,1.272433,15.812500,40.137500,3.702250,NaN,NaN,1643.531832
239,Sub-Saharan Africa (IDA & IBRD countries),NaN,NaN,5.538485,NaN,NaN,16.161908,39.019462,3.829487e+10,22.496782,-1.357705,NaN,14.978078,2.720355,27.852083,46.865957,7.264608,NaN,NaN,1463.853917
240,Trinidad and Tobago,NaN,NaN,3.060469,NaN,NaN,0.497160,53.250000,-2.396007e+07,35.428014,-6.292594,NaN,NaN,0.357424,10.500000,32.000000,4.373000,NaN,NaN,16352.109731
241,Tunisia,6.733311e+08,6.694000e+09,3.711015,NaN,NaN,9.220993,68.346000,6.951009e+08,24.431890,-0.040607,NaN,9.044365,1.142911,11.000000,60.200000,15.510000,NaN,NaN,3688.646375
242,Turkey,2.182767e+09,9.800200e+10,7.775134,41.9,NaN,6.183746,74.134000,1.334300e+10,28.183296,1.573437,NaN,24.471885,1.573012,6.500000,41.100000,10.840000,NaN,32.720547,10862.725380
243,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,60.645000,2.230000e+05,NaN,2.143597,NaN,NaN,0.868862,NaN,NaN,NaN,NaN,NaN,3295.720635
244,Tanzania,1.562454e+07,2.038494e+09,5.170320,NaN,NaN,29.233760,32.333000,1.365388e+09,24.932662,3.716354,NaN,23.713280,3.092454,28.000000,43.900000,2.168000,NaN,NaN,877.507612
245,Uganda,7.556939e+06,5.019120e+08,5.464428,42.8,NaN,23.708112,22.624000,6.257044e+08,20.676315,1.268515,NaN,19.659504,3.290872,26.000000,33.700000,2.010000,NaN,13.721044,580.383534
246,Ukraine,NaN,2.014782e+10,13.895038,25.0,NaN,11.631382,69.154000,3.441000e+09,22.986914,2.720932,NaN,18.989646,-0.331381,6.500000,52.300000,9.350000,NaN,33.535135,2185.728031
247,Upper middle income,6.649542e+11,1.431877e+12,2.000000,NaN,NaN,6.772647,64.607601,4.358199e+11,32.637614,3.119470,NaN,31.761224,0.767896,30.174510,38.603922,6.087050,NaN,NaN,7864.504365
248,Uruguay,1.486877e+08,NaN,9.639413,39.7,NaN,5.891940,95.144000,-3.791090e+08,25.539278,1.322074,NaN,16.736534,0.362269,6.500000,41.800000,7.840000,NaN,38.425205,15298.350892
249,United States,1.531870e+11,NaN,1.261583,41.5,NaN,1.014460,81.862000,4.794150e+11,18.880434,0.742795,NaN,18.093476,0.734307,5.600000,44.000000,4.870000,NaN,22.732077,57588.538071
250,Uzbekistan,NaN,3.463040e+08,NaN,NaN,NaN,16.114932,50.650000,6.650237e+07,30.080092,5.941724,NaN,NaN,1.738849,5.500000,38.100000,7.514000,NaN,18.411088,2105.870905
251,St. Vincent and the Grenadines,NaN,4.099000e+06,-0.149642,NaN,NaN,6.955975,51.373000,9.141302e+07,14.765338,1.096564,5.77971,NaN,0.171613,10.000000,39.300000,18.211000,NaN,NaN,6982.256556
252,"Venezuela, RB",NaN,2.882522e+10,254.948535,NaN,NaN,NaN,88.165000,1.587000e+09,NaN,NaN,NaN,NaN,1.317057,230.000000,65.400000,7.146000,NaN,NaN,NaN
253,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,46.957000,5.909679e+10,NaN,NaN,NaN,NaN,1.803452,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,95.480000,NaN,NaN,NaN,NaN,NaN,-0.185856,NaN,NaN,7.238000,NaN,NaN,NaN
255,Vietnam,NaN,1.400765e+10,3.243833,35.3,NaN,16.319644,34.510000,1.260000e+10,32.715042,5.090511,NaN,24.764248,1.060392,24.000000,39.400000,2.100000,NaN,NaN,2170.648054
256,Vanuatu,NaN,3.100000e+07,0.859402,NaN,NaN,NaN,25.062000,NaN,NaN,1.770194,NaN,NaN,2.167915,18.000000,8.500000,5.267000,NaN,25.328548,2913.967232
257,World,NaN,NaN,1.664825,NaN,NaN,3.546352,54.373003,2.448814e+12,25.399635,1.313278,NaN,24.450724,1.176992,21.314211,40.437037,5.531033,NaN,27.491683,10200.860601
258,Samoa,1.429820e+05,0.000000e+00,1.303857,NaN,NaN,9.589887,18.681000,2.524382e+06,23.894610,6.395084,4.08105,NaN,0.702526,9.000000,18.500000,8.487000,NaN,24.518390,4030.013144
259,Kosovo,NaN,6.210000e+08,0.300025,26.5,NaN,10.459906,NaN,2.437297e+08,23.797177,3.243771,NaN,18.950215,0.796024,6.000000,15.200000,NaN,NaN,NaN,3697.548026
260,"Yemen, Rep.",NaN,2.459200e+08,NaN,NaN,NaN,15.933935,35.394000,-5.610000e+08,91.194204,-35.929846,NaN,NaN,2.451502,40.500000,26.600000,13.729000,NaN,NaN,660.280885
261,South Africa,1.906054e+09,2.979100e+10,6.326264,NaN,NaN,2.178174,65.341000,2.215307e+09,26.009143,-0.734890,5.94303,16.355887,1.301374,45.000000,28.800000,26.549999,NaN,34.451406,5280.017633
262,Zambia,NaN,1.011090e+09,17.869960,NaN,NaN,6.228470,42.438000,6.628139e+08,34.877139,0.687855,NaN,31.345985,3.002816,8.500000,18.600000,7.777000,NaN,22.295369,1262.989682
263,Zimbabwe,1.374297e+07,2.985208e+09,-1.559789,NaN,NaN,9.735282,32.296000,3.430138e+08,20.191176,-1.707498,NaN,-0.744981,2.336070,91.000000,31.600000,5.046000,NaN,NaN,1029.076649

In [5]:
print(indic.indices.replace("_", " ").replace(".xls",""))

High-technology exports
External debt stocks short-term
Inflation consumer prices
GINI index
Researchers in R&D
Agriculture forestry and fishing value added
Urban population
Foreign direct investment net inflows
Industry (including construction) value added
GDP per capita growth
Government expenditure on education total
Gross savings
Population growth
Time required to start a business
Total tax rate
Unemployment total
Ease of doing business index
Expense
GDP per capita